version: '3.8'

services:
  #database section
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

#network section
networks:
  default:
    name: loyalty-app
    driver: bridge

#volumes sections
volumes:
  sqlserver_data:
    name: sqlserver_data